import React from 'react';
import './LoremIpsum.scss'

export default function LoremIpsum() {
    return (
        <div id='lorem-ipsum'>
            <h1>Lorem Ipsum</h1>
            <h4>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..." <br />
                "There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."</h4>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nibh tortor, finibus cursus dolor sed, mollis condimentum purus. Integer eros mauris, pretium id elit vel, consequat imperdiet enim. Proin finibus fermentum elit non varius. Morbi porttitor ex tellus, facilisis iaculis nisl egestas at. Integer venenatis congue ante, efficitur cursus ligula ornare id. Morbi ut massa imperdiet, tristique mauris vitae, ultricies sapien. In accumsan quis massa nec pretium. Sed ut dapibus massa, ut pulvinar leo. Curabitur elit tellus, eleifend eu est ut, blandit maximus tellus. Nam dolor orci, facilisis at facilisis molestie, suscipit dictum nisl. Sed convallis lobortis egestas. Cras a massa sit amet enim ornare tincidunt nec in arcu. Nulla malesuada posuere pretium. Sed tortor urna, tincidunt at posuere sed, condimentum dictum erat.</p>

            <p>Ut pharetra lacus nibh, ac blandit nisl accumsan eget. Ut varius mollis nibh sed ultricies. Quisque blandit sit amet nunc vel ultrices. Cras ac dignissim sem. In posuere lacinia libero, nec suscipit neque vestibulum quis. Suspendisse luctus a augue vel iaculis. Pellentesque justo justo, vehicula ac pharetra in, porta ut leo. Sed interdum tempor pharetra. Fusce sit amet erat finibus, feugiat lorem vitae, hendrerit sapien. Sed vehicula aliquet vulputate.</p>

            <p>Integer euismod mauris quis magna pellentesque porttitor. Vivamus ex urna, rutrum at rutrum id, tempus dignissim leo. Nam sapien nulla, blandit quis vehicula blandit, feugiat sit amet turpis. Quisque imperdiet mollis placerat. Phasellus eu eros sit amet libero commodo commodo. Cras luctus quis massa at ornare. Pellentesque sem elit, placerat vitae nisi at, bibendum cursus libero. Fusce eros mauris, fringilla at lectus vitae, mattis bibendum lacus. Aenean eget dolor at ipsum porttitor blandit. Vestibulum a tempor elit, ac bibendum magna. Morbi ac pretium mi, ut sagittis urna. Mauris interdum eget dolor id bibendum. Phasellus quis dui mattis, accumsan lacus at, bibendum dolor. Aliquam non nibh sed ipsum condimentum placerat.</p>

            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut bibendum nec sem quis sodales. Integer sodales dapibus venenatis. Fusce vel lobortis enim. Mauris lacus erat, scelerisque sit amet condimentum facilisis, venenatis venenatis elit. Morbi imperdiet, tortor eget tempus vehicula, nisl orci semper ligula, ac efficitur ex risus et massa. Donec ut nisl varius ligula euismod interdum at sed nulla. Sed at dui euismod, ornare arcu eget, tempor arcu. Cras et orci id justo euismod condimentum et ut diam. Cras justo lorem, accumsan vitae suscipit at, mattis eget nisi. Nam ut nibh eget libero finibus vehicula eget eu quam.</p>

            <p>Nam ac dui in felis venenatis accumsan et sed sapien. Etiam pharetra tortor id justo aliquet malesuada. Nam viverra augue tristique orci molestie tincidunt. Mauris convallis nunc nec pellentesque sodales. Nunc tincidunt, nisi at condimentum mollis, erat sem viverra purus, vitae tristique quam dolor nec turpis. Donec laoreet lorem ac sapien lobortis, laoreet vestibulum arcu cursus. Nulla laoreet sapien nisi, id vehicula quam euismod ac.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nibh tortor, finibus cursus dolor sed, mollis condimentum purus. Integer eros mauris, pretium id elit vel, consequat imperdiet enim. Proin finibus fermentum elit non varius. Morbi porttitor ex tellus, facilisis iaculis nisl egestas at. Integer venenatis congue ante, efficitur cursus ligula ornare id. Morbi ut massa imperdiet, tristique mauris vitae, ultricies sapien. In accumsan quis massa nec pretium. Sed ut dapibus massa, ut pulvinar leo. Curabitur elit tellus, eleifend eu est ut, blandit maximus tellus. Nam dolor orci, facilisis at facilisis molestie, suscipit dictum nisl. Sed convallis lobortis egestas. Cras a massa sit amet enim ornare tincidunt nec in arcu. Nulla malesuada posuere pretium. Sed tortor urna, tincidunt at posuere sed, condimentum dictum erat.</p>

            <p>Ut pharetra lacus nibh, ac blandit nisl accumsan eget. Ut varius mollis nibh sed ultricies. Quisque blandit sit amet nunc vel ultrices. Cras ac dignissim sem. In posuere lacinia libero, nec suscipit neque vestibulum quis. Suspendisse luctus a augue vel iaculis. Pellentesque justo justo, vehicula ac pharetra in, porta ut leo. Sed interdum tempor pharetra. Fusce sit amet erat finibus, feugiat lorem vitae, hendrerit sapien. Sed vehicula aliquet vulputate.</p>

            <p>Integer euismod mauris quis magna pellentesque porttitor. Vivamus ex urna, rutrum at rutrum id, tempus dignissim leo. Nam sapien nulla, blandit quis vehicula blandit, feugiat sit amet turpis. Quisque imperdiet mollis placerat. Phasellus eu eros sit amet libero commodo commodo. Cras luctus quis massa at ornare. Pellentesque sem elit, placerat vitae nisi at, bibendum cursus libero. Fusce eros mauris, fringilla at lectus vitae, mattis bibendum lacus. Aenean eget dolor at ipsum porttitor blandit. Vestibulum a tempor elit, ac bibendum magna. Morbi ac pretium mi, ut sagittis urna. Mauris interdum eget dolor id bibendum. Phasellus quis dui mattis, accumsan lacus at, bibendum dolor. Aliquam non nibh sed ipsum condimentum placerat.</p>

            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut bibendum nec sem quis sodales. Integer sodales dapibus venenatis. Fusce vel lobortis enim. Mauris lacus erat, scelerisque sit amet condimentum facilisis, venenatis venenatis elit. Morbi imperdiet, tortor eget tempus vehicula, nisl orci semper ligula, ac efficitur ex risus et massa. Donec ut nisl varius ligula euismod interdum at sed nulla. Sed at dui euismod, ornare arcu eget, tempor arcu. Cras et orci id justo euismod condimentum et ut diam. Cras justo lorem, accumsan vitae suscipit at, mattis eget nisi. Nam ut nibh eget libero finibus vehicula eget eu quam.</p>

            <p>Nam ac dui in felis venenatis accumsan et sed sapien. Etiam pharetra tortor id justo aliquet malesuada. Nam viverra augue tristique orci molestie tincidunt. Mauris convallis nunc nec pellentesque sodales. Nunc tincidunt, nisi at condimentum mollis, erat sem viverra purus, vitae tristique quam dolor nec turpis. Donec laoreet lorem ac sapien lobortis, laoreet vestibulum arcu cursus. Nulla laoreet sapien nisi, id vehicula quam euismod ac.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nibh tortor, finibus cursus dolor sed, mollis condimentum purus. Integer eros mauris, pretium id elit vel, consequat imperdiet enim. Proin finibus fermentum elit non varius. Morbi porttitor ex tellus, facilisis iaculis nisl egestas at. Integer venenatis congue ante, efficitur cursus ligula ornare id. Morbi ut massa imperdiet, tristique mauris vitae, ultricies sapien. In accumsan quis massa nec pretium. Sed ut dapibus massa, ut pulvinar leo. Curabitur elit tellus, eleifend eu est ut, blandit maximus tellus. Nam dolor orci, facilisis at facilisis molestie, suscipit dictum nisl. Sed convallis lobortis egestas. Cras a massa sit amet enim ornare tincidunt nec in arcu. Nulla malesuada posuere pretium. Sed tortor urna, tincidunt at posuere sed, condimentum dictum erat.</p>

            <p>Ut pharetra lacus nibh, ac blandit nisl accumsan eget. Ut varius mollis nibh sed ultricies. Quisque blandit sit amet nunc vel ultrices. Cras ac dignissim sem. In posuere lacinia libero, nec suscipit neque vestibulum quis. Suspendisse luctus a augue vel iaculis. Pellentesque justo justo, vehicula ac pharetra in, porta ut leo. Sed interdum tempor pharetra. Fusce sit amet erat finibus, feugiat lorem vitae, hendrerit sapien. Sed vehicula aliquet vulputate.</p>

            <p>Integer euismod mauris quis magna pellentesque porttitor. Vivamus ex urna, rutrum at rutrum id, tempus dignissim leo. Nam sapien nulla, blandit quis vehicula blandit, feugiat sit amet turpis. Quisque imperdiet mollis placerat. Phasellus eu eros sit amet libero commodo commodo. Cras luctus quis massa at ornare. Pellentesque sem elit, placerat vitae nisi at, bibendum cursus libero. Fusce eros mauris, fringilla at lectus vitae, mattis bibendum lacus. Aenean eget dolor at ipsum porttitor blandit. Vestibulum a tempor elit, ac bibendum magna. Morbi ac pretium mi, ut sagittis urna. Mauris interdum eget dolor id bibendum. Phasellus quis dui mattis, accumsan lacus at, bibendum dolor. Aliquam non nibh sed ipsum condimentum placerat.</p>

            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut bibendum nec sem quis sodales. Integer sodales dapibus venenatis. Fusce vel lobortis enim. Mauris lacus erat, scelerisque sit amet condimentum facilisis, venenatis venenatis elit. Morbi imperdiet, tortor eget tempus vehicula, nisl orci semper ligula, ac efficitur ex risus et massa. Donec ut nisl varius ligula euismod interdum at sed nulla. Sed at dui euismod, ornare arcu eget, tempor arcu. Cras et orci id justo euismod condimentum et ut diam. Cras justo lorem, accumsan vitae suscipit at, mattis eget nisi. Nam ut nibh eget libero finibus vehicula eget eu quam.</p>

            <p>Nam ac dui in felis venenatis accumsan et sed sapien. Etiam pharetra tortor id justo aliquet malesuada. Nam viverra augue tristique orci molestie tincidunt. Mauris convallis nunc nec pellentesque sodales. Nunc tincidunt, nisi at condimentum mollis, erat sem viverra purus, vitae tristique quam dolor nec turpis. Donec laoreet lorem ac sapien lobortis, laoreet vestibulum arcu cursus. Nulla laoreet sapien nisi, id vehicula quam euismod ac.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nibh tortor, finibus cursus dolor sed, mollis condimentum purus. Integer eros mauris, pretium id elit vel, consequat imperdiet enim. Proin finibus fermentum elit non varius. Morbi porttitor ex tellus, facilisis iaculis nisl egestas at. Integer venenatis congue ante, efficitur cursus ligula ornare id. Morbi ut massa imperdiet, tristique mauris vitae, ultricies sapien. In accumsan quis massa nec pretium. Sed ut dapibus massa, ut pulvinar leo. Curabitur elit tellus, eleifend eu est ut, blandit maximus tellus. Nam dolor orci, facilisis at facilisis molestie, suscipit dictum nisl. Sed convallis lobortis egestas. Cras a massa sit amet enim ornare tincidunt nec in arcu. Nulla malesuada posuere pretium. Sed tortor urna, tincidunt at posuere sed, condimentum dictum erat.</p>

            <p>Ut pharetra lacus nibh, ac blandit nisl accumsan eget. Ut varius mollis nibh sed ultricies. Quisque blandit sit amet nunc vel ultrices. Cras ac dignissim sem. In posuere lacinia libero, nec suscipit neque vestibulum quis. Suspendisse luctus a augue vel iaculis. Pellentesque justo justo, vehicula ac pharetra in, porta ut leo. Sed interdum tempor pharetra. Fusce sit amet erat finibus, feugiat lorem vitae, hendrerit sapien. Sed vehicula aliquet vulputate.</p>

            <p>Integer euismod mauris quis magna pellentesque porttitor. Vivamus ex urna, rutrum at rutrum id, tempus dignissim leo. Nam sapien nulla, blandit quis vehicula blandit, feugiat sit amet turpis. Quisque imperdiet mollis placerat. Phasellus eu eros sit amet libero commodo commodo. Cras luctus quis massa at ornare. Pellentesque sem elit, placerat vitae nisi at, bibendum cursus libero. Fusce eros mauris, fringilla at lectus vitae, mattis bibendum lacus. Aenean eget dolor at ipsum porttitor blandit. Vestibulum a tempor elit, ac bibendum magna. Morbi ac pretium mi, ut sagittis urna. Mauris interdum eget dolor id bibendum. Phasellus quis dui mattis, accumsan lacus at, bibendum dolor. Aliquam non nibh sed ipsum condimentum placerat.</p>

            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut bibendum nec sem quis sodales. Integer sodales dapibus venenatis. Fusce vel lobortis enim. Mauris lacus erat, scelerisque sit amet condimentum facilisis, venenatis venenatis elit. Morbi imperdiet, tortor eget tempus vehicula, nisl orci semper ligula, ac efficitur ex risus et massa. Donec ut nisl varius ligula euismod interdum at sed nulla. Sed at dui euismod, ornare arcu eget, tempor arcu. Cras et orci id justo euismod condimentum et ut diam. Cras justo lorem, accumsan vitae suscipit at, mattis eget nisi. Nam ut nibh eget libero finibus vehicula eget eu quam.</p>

            <p>Nam ac dui in felis venenatis accumsan et sed sapien. Etiam pharetra tortor id justo aliquet malesuada. Nam viverra augue tristique orci molestie tincidunt. Mauris convallis nunc nec pellentesque sodales. Nunc tincidunt, nisi at condimentum mollis, erat sem viverra purus, vitae tristique quam dolor nec turpis. Donec laoreet lorem ac sapien lobortis, laoreet vestibulum arcu cursus. Nulla laoreet sapien nisi, id vehicula quam euismod ac.</p>

        </div>
    )
}